### PR TITLE
Lower required Android version

### PR DESCRIPTION
**Pull request by niccokunzmann**
Having a web server on the phone is really important for old phones as more complicated applications for synchronizing files do not work for them (Syncthing, nextCloud, ...). HTTP-Servers are an easy way to exchange files peer to peer.

I have an old phone and reduced the android version so that the server runs on it.

Changes:
- minAPK version
- remove notifications if they are not available
- use commit instead of apply

I kindly request a merge of this to provide a means of sharing files to underprivileged users with old phones.

### CODE REVIEW

**Comment by mvbasov** [comment]
Thank you for contribution to this project!
The main problem is testing on legacy hardware. My the oldest hardware has Android 4.2.2 (API 17).
As you tell modification operate on API 5. Which kind of hardware do you used? Did you test HTTP `multipart/byteranges`? Did you test for big files (>5Mb)?

**Comment by niccokunzmann** [comment]
I have API level 10.

> The main problem is testing on legacy hardware. My the oldest hardware has Android 4.2.2 (API 17).
As you tell modification operate on API 5. Which kind of hardware do you used? Did you test HTTP multipart/byteranges? Did you test for big files (>5Mb)?

That might seem like a problem. However, I have another view on it: Access
The package was usable from level 16 on. Now it is usable from level 5 on.
I could test it with level 10 and it works. Android Studio also showed all version incompatibilities vith version 5 and I handled them.
From version 10 on it is usable by me. You helped +1 person :)
By lowering the version number, you give access to more people with a reduced set of features. If there are small bugs, they can still try to use the software instead of being prevented from using it. Having it available at version 5 makes it much easier to find people to maintain and test it at that level than raising the version number.

> Which kind of hardware do you used?

HTC Desire S, Android 2.3.5

> Did you test HTTP multipart/byteranges?

How would I test these?

> Did you test for big files (>5Mb)?

No, still I will use the software because I need some way to transfer files.

**Comment by mvbasov** [comment]
Did you test HTTP multipart/byteranges?

    How would I test these?

The simplest way is to play video and seek to some moment in the future. If it start playing immediately this feature operate.

About min API. Change `minSdkVersion` to 10, because you want to merge to `master` branch.
At the beta release time I will change it to 5 for testing.

**Comment by niccokunzmann** [comment]
- [X] android 10
- [x] The simplest way is to play video and seek to some moment in the future.

@mvbasov Thanks. It works.

**Comment by mvbasov** [comment]
This is my `pet project` don't wait super fast reaction from me :)
Play Market and F-Droid versions will be updated during this week.

**Pull request merged**
