### PR TITLE
Cleanup and small performance improvements

### PR DESCRIPTION
**Pull request by stokito**
Embedded Android devices are slow so it makes sense to do some basic optimizations.
Almost all these optimization was just made automatically by Android Studio so the refactoring should is safe.

### CODE REVIEW

**Comment by stokito** [comment]
Hi @mvbasov please take a look on the PR. I would like to send another PR but I want to know if the project is alive

**Comment by mvbasov** [comment]
Thank You for your work!
Project is alive but I spent only free time for it.
1/2 year reaction time is normal for this project ;)

**Comment by mvbasov** [comment]
You warm up my interest to this project:)
The main problem of this project now is reaction to switch network.
The main idea is:
- I don't allow to application work on cellular network (for security reason). It is done
- Server need to disconnect if network changed. It is done
- Server need to bind to all kind of local network interfaces:
  - WiFi (done)
  - Ethernet (for using on TV boxes)(not done)
  - On all kind of tethering interfaces (done only for WiFi tethering)
  - As fallback bind to loopback (done)

**Comment by stokito** [comment]
Thank you. Basically I’m interested in your server because it’s the only one available on my xiomi Android TV installed via F-droid. I saw few other http and even webdav servers in App Store but looks like only your supports TV boxes.
To be honest you can just include Jetty webserver or maybe even tomcat embedded. They are much bigger but already supported, audited and well known.

**Comment by mvbasov** [comment]
You will be laugh. It not operate on my TV box :)
I need more free time to implement handling ethernet connection:(
Jetty web server is a good solution but "killer feature" of this project is to be lightweight. See name of this project.
The idea was write simplest web server for Android. It can be good base for another projects as I think. 
The F-Droid release will be little bit later. I need to test new code. Also F-Droid ecosystem has very complex release workflow...

**Pull request merged**
